### ISSUE TITLE
Bluetooth hardware setup

### ISSUE THREAD

**Issue by mangkoran** [skarrmann/zmk-config#1]
Hi Steven. I've been daily driving morizon for the past 2 years and I would like to thank you for providing this board design.

Recently I'm interested to make morizon wireless. May I ask how do you setup the hardware of bluetooth microcontroller on the board (especially the battery/power)? AFAIK (h/m)orizon have no power switch and battery pinout.

**Comment by skarrmann** [comment]
Hi @mangkoran! I am glad you have been enjoying Morizon over the past couple years.

As you correctly observed, (H/M)orizon does not have dedicated pinouts or parts for connecting a battery and a power switch. Nonetheless, it is still possible to make the keyboard wireless, and with nice power management thanks to ZMK features.

For the dev board, you can use either a nice!nano or a SuperMini nRF52840.

Solder sockets to the (H/M)orizon PCB and the dev board, making sure they give enough room to fit a 301230 battery underneath it. You only need about 4mm of space, so most sockets will work.

Cut the battery wires so they are just long enough to poke through the B+/B- pins from the underside of the dev board. Solder the battery wires to these pins. Use a piece of Kapton or electrical tape to secure the battery to the dev board. It should look something like this:

https://github.com/user-attachments/assets/d3a76e41-2aba-4529-8b6c-b7505fce7068

In ZMK, the [Soft Off Feature](https://zmk.dev/docs/features/soft-off) allows the keyboard to be powered off with a key binding, and then turned back on with the reset button. This power management solution works very well given the absence of a physical power switch.

It has been a while since I've updated the ZMK configuration for these keyboards, and I should add proper documentation for this wireless setup in the main repository. I will make these updates later this week.

Let me know if this helps, and if you have any other questions!

**Comment by mangkoran** [comment]
Thank you for your thorough explanation. TIL ZMK has soft off feature, which is surely helpful in this case (and other Pro Micro boards). I'll give this a shot on my spare time. I have SuperMinis waiting in my drawer for several months already, and new switches and other parts on the way.

**Comment by skarrmann** [comment]
My pleasure, and have fun with your next keyboard build!

I updated the Horizon/Morizon ZMK configuration to include the Soft Off feature, and tested it yesterday. Turning off the keyboard this way worked as expected with my hardware on Android and Arch Linux. However, Windows 11 did not cleanly clear the bluetooth connection when turning off the keyboard this way, and other ZMK users have reported issues on this operating system depending on their drivers. This issue could be due to user error on my part, so this is just a heads up in case the Soft Off feature isn't completely reliable for your setup.

I will keep this issue open until I update the wireless setup instructions. Thank you for reaching out.

**Comment by skarrmann** [comment]
The documentation now clarifies the bluetooth hardware setup.

In the Horizon repository, the battery installation is now described. It also clarifies that no power switch or battery connector is used. The updates in the bill of materials section, since that's where the battery part is noted: https://github.com/skarrmann/horizon?tab=readme-ov-file#bill-of-materials

Please reach out if you have any more questions!
